# Generated by Django 4.2.4 on 2023-09-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articl',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='articl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/main/img/', verbose_name='Изображение'),
        ),
    ]
