# Generated by Django 4.2.4 on 2023-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_articl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articl',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Изображение'),
        ),
    ]
